classes:
  - common
  - manifests.metallb
  - component.secrets
  - component.configmaps

parameters:
  target_name: metallb
  namespace: metallb-system
  context: kubernetes-admin@glab.dev
  addresses: 192.168.2.100-192.168.2.120
  secrets:
    memberlist:
      data:
        secretkey: ?{awskms:targets/${target_name}/memberlist||randomstr|base64}
  configmaps:
    config:
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - ${addresses}