repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/GilmanLab/precommit
    rev: v1.0.0
    hooks:
      - id: jsonnetfmt
