apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Tiller
    release: nfs
  name: run-nfs-nfs-client-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfs-nfs-client-provisioner-runner
subjects:
  - kind: ServiceAccount
    name: nfs-nfs-client-provisioner
    namespace: nfs
