apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Tiller
    release: nfs
  name: leader-locking-nfs-nfs-client-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-locking-nfs-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-nfs-client-provisioner
    namespace: nfs
