allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Tiller
    release: nfs
  name: nfs
parameters:
  archiveOnDelete: 'true'
provisioner: cluster.local/nfs-nfs-client-provisioner
reclaimPolicy: Delete
