classes:
  - manifests.cert-manager
  - component.secrets
  - component.clusterissuer

parameters:
  issuer:
    name: letsencrypt
    acme:
      email: ${environment:acme:email}
      server: ${environment:acme:server}
    cloudflare:
      email: ${environment:cloudflare:email}
      secret:
        name: cloudflare-api-token
        key: token
  secrets:
    cloudflare-api-token:
      data:
        token: ?{awskms:cloudflare-token}