apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: nginx-nginx-ingress
    helm.sh/chart: nginx-ingress-0.5.0
  name: nginx-nginx-ingress-leader-election
  namespace: nginx
