apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: nginx-nginx-ingress
    helm.sh/chart: nginx-ingress-0.5.0
  name: nginx-nginx-ingress
  namespace: nginx
spec:
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: nginx-nginx-ingress
  type: LoadBalancer
