apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: nginx-nginx-ingress
    helm.sh/chart: nginx-ingress-0.5.0
  name: transportservers.k8s.nginx.org
spec:
  group: k8s.nginx.org
  names:
    kind: TransportServer
    plural: transportservers
    shortNames:
      - ts
    singular: transportserver
  preserveUnknownFields: false
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: TransportServer defines the TransportServer resource.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TransportServerSpec is the spec of the TransportServer resource.
          properties:
            action:
              description: Action defines an action.
              properties:
                pass:
                  type: string
              type: object
            host:
              type: string
            listener:
              description: TransportServerListener defines a listener for a TransportServer.
              properties:
                name:
                  type: string
                protocol:
                  type: string
              type: object
            upstreamParameters:
              description: UpstreamParameters defines parameters for an upstream.
              properties:
                udpRequests:
                  type: integer
                udpResponses:
                  type: integer
              type: object
            upstreams:
              items:
                description: Upstream defines an upstream.
                properties:
                  name:
                    type: string
                  port:
                    type: integer
                  service:
                    type: string
                type: object
              type: array
          type: object
      type: object
  versions:
    - name: v1alpha1
      served: true
      storage: true
