apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: nginx-nginx-ingress
    helm.sh/chart: nginx-ingress-0.5.0
  name: nginx-nginx-ingress
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-nginx-ingress
  template:
    metadata:
      annotations:
        prometheus.io/port: '9113'
        prometheus.io/scrape: 'true'
      labels:
        app: nginx-nginx-ingress
    spec:
      containers:
        - args:
            - -nginx-plus=false
            - -nginx-configmaps=$(POD_NAMESPACE)/nginx-nginx-ingress
            - -default-server-tls-secret=$(POD_NAMESPACE)/nginx-nginx-ingress-default-server-secret
            - -ingress-class=nginx
            - -use-ingress-class-only=false
            - -health-status=false
            - -health-status-uri=/nginx-health
            - -nginx-debug=false
            - -v=1
            - -nginx-status=true
            - -nginx-status-port=8080
            - -nginx-status-allow-cidrs=127.0.0.1
            - -report-ingress-status
            - -external-service=nginx-nginx-ingress
            - -enable-leader-election=true
            - -leader-election-lock-name=nginx-nginx-ingress-leader-election
            - -enable-prometheus-metrics=true
            - -prometheus-metrics-listen-port=9113
            - -enable-custom-resources=true
            - -enable-tls-passthrough=false
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: nginx/nginx-ingress:edge
          imagePullPolicy: IfNotPresent
          name: nginx-nginx-ingress
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 9113
              name: prometheus
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            runAsUser: 101
      hostNetwork: false
      serviceAccountName: nginx-nginx-ingress
